supabase/migrations/20250510122416_add_first_tables.sql

ユーザーテーブルにセンシティブな情報を含むが、そのアクセス制限を強化した。
- ユーザー登録時に入力するprivate_usersは認証した本人のみがアクセス可能
- 一般ユーザーでも閲覧可能なユーザー情報はpublic_user_profilesテーブルに配置し、内容はprivate_usersのうち公開情報となるものを保持するように(トリガーでデータを取り込んでいるがやりすぎな気もする)

fix: ユーザー関連のテーブルのアクセス制限を強化 & 各テーブルへRLS設定を追加

---

docs/sitemap.md

feat: sitemapを追加

---

app/page.tsx
app/user/[id]/page.tsx
components/activity-timeline.tsx
supabase/migrations/20250510122416_add_first_tables.sql
utils/types/supabase.ts

色々後で調整が必要と思いますがまずはざっくり。
- ちゃんとマイグレーションしてないので supabase db reset 必要です
- 共通コンポーネントはいったん components 直下においてます
- トップの活動タイムラインも共通コンポーネントで置き換えました
調整すべき事項
- 表示最大件数
- ページング仕様(もっと見るで20件ずつ下に行が追加されているとか？)
関連Issue
- #27

ユーザー詳細ページ作成とタイムラインコンポーネント

---

lefthook.yml
package-lock.json
package.json

lefthookを導入して自動で biome check がかかるようにする

---

app/missions/[id]/complete/ShareButton.tsx
app/missions/[id]/complete/ShareTwitterButton.tsx
app/missions/[id]/complete/page.tsx

- 機能のみ実装
- Xでのシェア、navigator.share()によるシェアボタンの実装
- navigator.share() はデスクトップだと微妙なので非表示
X以外にちゃんと対応した方がいいサービスがあればご指摘ください。facebookとLINEあたりはあった方がいい？
関連Issue
#26

feat: シェアボタンの実装

---

app/users/[id]/page.tsx
components/activity-timeline.tsx

- URL変更 /user/:id => /users/:id
- async function なのに params に await が付いてなかった

ユーザーページのURLと警告修正

---

app/layout.tsx
app/page.tsx
components/activities.tsx
components/activity-timeline.tsx
components/events.tsx
components/header-auth.tsx
components/missions.tsx
components/navbar.tsx
components/progress.tsx

このPRでは、ダッシュボードのUI改善として以下の変更を行いました：
1. UI構造の改善：大きなpage.tsxファイルから機能ごとにコンポーネントを分離
2. コンポーネントの再利用性向上：Activities、Events、Missions、Progressなどの独立したコンポーネント化
3. ナビゲーションの追加：アプリ全体のナビゲーションバーを実装
4. スタイルの一貫性向上：境界線やパディングなどのスタイル調整
- 新規コンポーネント追加: 
- navbar.tsx: サイト全体のナビゲーションバー
- activities.tsx: 活動タイムライン表示用コンポーネント
- missions.tsx: ミッション表示用コンポーネント
- events.tsx: イベント表示用コンポーネント
- progress.tsx: 進捗表示用コンポーネント
- app/page.tsx: 大幅リファクタリングによる可読性向上
- スタイル調整: パディング・マージンの標準化とカード境界線の改善

#23 トップページのコンポーネントの分割

---

app/users/[id]/page.tsx
app/users/[id]/user-detail-activities.tsx
components/activities.tsx
components/activity-timeline.tsx

活動タイムラインのページング実装

---

app/page.tsx
components/progress.tsx

初期スコープで不要の表示をコメントアウト

---

components/activity-timeline.tsx
components/user-avatar.tsx
supabase/migrations/20250510122416_add_first_tables.sql
utils/types/supabase.ts

タイムラインのアイテムごとにクエリが発行されている問題の修正。

活動タイムラインのN+1の修正

---

app/(auth-pages)/sign-up/SignUpForm.tsx
app/(auth-pages)/sign-up/page.tsx

利用規約・プライバシポリシーへの同意チェックボックス追加

---

.github/CODEOWNERS

CODEOWNERSの設定が間違っていたので修正

---

app/globals.css
components/ui/button.tsx
stories/basic/Accordion.stories.tsx
stories/basic/All.stories.tsx
stories/basic/Avatar.stories.tsx
stories/basic/Badge.stories.tsx
stories/basic/Button.stories.tsx
stories/basic/Card.stories.tsx
stories/basic/Checkbox.stories.tsx
stories/basic/Dialog.stories.tsx
stories/basic/DropdownMenu.stories.tsx
stories/basic/Input.stories.tsx
stories/basic/Label.stories.tsx
stories/basic/Select.stories.tsx

各コンポーネントのstorybookと全基本コンポーネントを一覧できるstorybookを作成しました。claudeさんが。

基本コンポーネントのstorybook作成とトンマナ調整

---

app/missions/[id]/_components/MissionFormWrapper.tsx
app/missions/[id]/_components/SubmissionItem.tsx
app/missions/[id]/page.tsx
components/mission/mission-achievement-status.tsx
components/mission/mission.tsx

デザインシステムを使っていないところの修正とミッション関連のデザイン微修正

---

components/metric-card.tsx

fix: #122 
- toLocalString() を追加し3桁区切りにしました

feat: number formatの導入

---

.github/workflows/build_test.yaml
playwright.config.ts

localhostを指定すると治るらしい？
https://github.com/microsoft/playwright/issues/16834

Playwrightでタイムアウトになる問題の対策

---

app/missions/[id]/_components/MissionFormWrapper.tsx
app/missions/[id]/_hooks/useMissionSubmission.ts
app/missions/[id]/page.tsx

ミッションUIのログアウト状態におけるUI改善

---

components/metric-card.tsx
components/mission/mission.tsx

ミッションとカードのアニメーション削除。メトリクスとミッションのカードのshadowを合わせる。

---

cloudbuild.yaml

Supabase の config も cloudbuild で push するようにする
以前は権限が不足していて push できなかったが権限付与済み

Supabase の config も cloudbuild で push するようにする

---

CLAUDE.md

- タイトル通り
- Claude Codeを利用する方向けにあると便利かと考えた

feat: claude code用の概要ファイルCLAUDE.mdを追加

---

supabase/migrations/20250531135451_add_ogp_image_url_to_missions.sql

missionにogp画像パスを追加
https://team-mirai-volunteer.slack.com/archives/C08SNQ7D29L/p1748609943065989?thread_ts=1748402683.608299&cid=C08SNQ7D29L

missionにogp画像パスを追加

---

stories/Mission.stories.tsx

- ogp_image_url を追加
もう一箇所コケてそうだが別途
- build がコケてる。

fix ogp_image_url: Add ogp_image_url to dummyMission in stories

---

app/missions/[id]/_components/MissionFormWrapper.tsx
components/mission/ArtifactForm.tsx
components/ui/button.tsx
lib/types/supabase.ts

成果物ごとのラベルを表示

---

app/missions/[id]/_components/MissionFormWrapper.tsx

ミッションの注意文追加

---

app/layout.tsx
app/missions/[id]/_components/MissionCompleteDialog.tsx
app/missions/[id]/_components/MissionFormWrapper.tsx
app/missions/[id]/_components/ShareUrlButton.tsx
components/ui/sonner.tsx
package-lock.json
package.json

close https://github.com/team-mirai-volunteer/action-board/issues/219

シェアURLコピーボタンを追加

---

stories/Mission.stories.tsx

Fix build error

---

terraform/nextjs-app/cloud_build.tf

- NEXT_PUBLIC_XXX を build 時に環境変数として渡すように変更
- build 時にも渡さないといけない

NEXT_PUBLIC_XXX を build 時に環境変数として渡すように変更

---

app/missions/[id]/_components/MissionCompleteDialog.tsx

Fix LINE share

---

supabase/templates/confirmation.html
supabase/templates/email_change.html
supabase/templates/invite.html
supabase/templates/magic_link.html
supabase/templates/recovery.html

Fig email logo

---

.env.example
.github/workflows/build_test.yaml
cloudbuild.yaml
supabase/config.toml

fix: ローカルではSMTPを利用せず、Inbuketにメールが届くように & 本番ではSMTPを利用するように設定ファイルを修正

---

README.md

- 環境構築の手順の追加と変更
- https://github.com/team-mirai-volunteer/action-board/issues/267

READMEの環境構築手順を変更

---

app/footer.tsx
app/page.tsx

- notionのリンク切れを解消
- https://github.com/team-mirai-volunteer/action-board/issues/291

fix: update feedback link in footer and page components

---

components/header-auth.tsx
components/navbar.tsx

- Dropdown Menuにaria-labelを追加
- lighthouseで怒られていた。

fix: add aria-label to DropdownMenuTrigger for accessibility

---

instrumentation-client.ts
next.config.ts
sentry.edge.config.ts
sentry.server.config.ts

- SentryにSource Mapを送るようにする
- https://github.com/team-mirai-volunteer/action-board/issues/272

feat: add sourcemaps configuration for improved error stack traces

---

next.config.ts

- SentryのReleasesの設定
- https://github.com/team-mirai-volunteer/action-board/issues/272

Add release configuration for Sentry in next.config.ts

---

app/globals.css
app/page.tsx
components/hero.tsx
components/level-progress.tsx
components/levels.tsx
components/mission/missions.tsx
components/ui/button.tsx
components/ui/progress-circle.tsx
lib/services/userLevel.ts
lib/services/users.ts
tailwind.config.ts
tests/services/userLevel.test.ts

- トップにレベルとポイントを表示
- トップにレベルとポイントを表示

#282 トップにレベルとポイントを表示

---

app/(protected)/settings/profile/ProfileForm.tsx
lib/address.ts
next.config.ts

- 海外居住の方に対応できるように、都道府県の選択欄に”海外”を追加
- 海外居住者対応のため
Fixes #294

#294 海外居住の方対応

---

README.md

Reverts team-mirai-volunteer/action-board#324

Revert "docs : Windowsユーザー向けの環境構築の備忘録を追記"

---

app/page.tsx
app/ranking/page.tsx
components/ranking/current-user-card.tsx
components/ranking/ranking-icon.tsx
components/ranking/ranking-level-badge.tsx
components/ranking/ranking-top.tsx
lib/utils/ranking-utils.ts

- ランキングページを追加
-  自分のランキング(#285)
- TOP100(#284)
スマホ(UserLevelありとなし)
PC(UserLevelありとなし)

ランキングページの追加

---

app/actions.ts
app/missions/[id]/_lib/data.ts

紹介ミッションでXP付与

---

app/missions/[id]/_components/MissionWithSubmissionHistory.tsx
components/level-up-check.tsx
supabase/migrations/20250607041000_add_referral_mission.sql

紹介ミッションデータ修正

---

terraform/nextjs-app/secrets.tf

https://github.com/team-mirai-volunteer/action-board/pull/347/files#r2134741270  の修正

secret_data_woに戻す

---

cloudbuild.yaml

https://github.com/team-mirai-volunteer/action-board/pull/347#discussion_r2134742237 の修正

NEXT_PUBLIC_APP_ORIGINのcloudbuild修正

---

cloudbuild.yaml
next.config.ts

Deploy develop infra

---

next.config.ts

すいません、 false ではなく undefined にする必要があります

set setcommits to undefined

---

app/missions/[id]/_components/MissionWithSubmissionHistory.tsx

QRコード側はSSRされてる？せいなのかwindow.originにアクセスできてないぽいので

SSR用にprocess.env.NEXT_PUBLIC_APP_ORIGINを使用

---

cloudbuild.yaml

Fix NEXT_PUBLIC_APP_ORIGIN for cloudbuild

---

lib/supabase/server.ts

Supabaseの環境変数がないときに例外をはくように

---

app/api/batch/backfill-missing-xp/route.ts
lib/services/userLevel.ts
lib/supabase/server.ts
lib/utils/supabase-utils.ts

本番デプロイ 6/9 3:21

---

components/mission/missions.tsx
supabase/migrations/20250611165705_add_missions_is_hidden.sql

close https://github.com/team-mirai-volunteer/action-board/issues/397

ミッションを非表示にできるように

---

.github/PULL_REQUEST_TEMPLATE.md

- PRテンプレートにissueが自動でクローズされる文言追加
- close忘れが存在する

feat: PRテンプレートにissue自動クローズ機能を追加

---

app/missions/[id]/actions.ts
supabase/migrations/20250611105031_add_join_speech.sql

- add #400 街頭演説参加ミッションの追加
- https://www.notion.so/team-mirai/20ff6f56bae18026b1dddcb6218a0c06?source=copy_link

[add #400] 街頭演説参加ミッションの追加

---

supabase/migrations/20250612120000_update_posting_mission_content.sql

- ポスティングミッションのcontentを更新
- ポスティングミッションのcontentを更新
- closes #379 

#379 ポスティングミッションのcontentを更新

---

supabase/migrations/20250612032337_add_watch_youtube_mission.sql

- ミッション「YouTube動画を視聴しよう」を追加
- Notion: https://team-mirai.notion.site/YouTube-20ff6f56bae1809cbd29d043e0610e5b
- closes #391 

YouTube動画を視聴しようミッションの追加

---

app/(protected)/settings/profile/ProfileForm.tsx
app/missions/[id]/actions.ts
components/mission/ArtifactForm.tsx
lib/constants.ts

ポスティングのポイントを1枚10ptに

---

README.md

README のセットアップ手順に振ってある番号に、若干誤りがあったので、修正しました。
- 環境構築をしているときに、どこまで進めたか混乱してしまったため。

docs(fix): ナンバリングが間違っていたので修正

---

components/header-auth.tsx
components/navbar.tsx
components/ranking/ranking-mission.tsx

本番デプロイ 06/22 15:09

---

app/page.tsx
components/mission/MissionsByCategory.tsx

カテゴリ別ミッションUI調整

---

supabase/migrations/20250624081700_add_slug_to_missions.sql

本番デプロイ 06/25 02:59

---

components/mission/MissionsByCategory.tsx

本番デプロイ 06/25 03:58

---

app/missions/[id]/_components/MissionFormWrapper.tsx

クリア上限なしのミッションで、クリア後にフォームがなくなるバグを修正

---

components/mission/MissionsByCategory.tsx

本番デプロイ 06/25 09:58

---

app/missions/[id]/_components/MainLinkButton.tsx
app/missions/[id]/_components/MissionFormWrapper.tsx
app/missions/[id]/_components/MissionWithSubmissionHistory.tsx
app/missions/[id]/_lib/data.ts
app/missions/[id]/_lib/types.ts
app/missions/[id]/actions.ts
app/missions/[id]/page.tsx
components/mission/MissionDetails.tsx
lib/artifactTypes.ts
lib/types/supabase.ts
mission_data/category_links.yaml
mission_data/mission_main_links.yaml
mission_data/missions.yaml
mission_data/src/export.ts
mission_data/src/sync.ts
mission_data/src/types.ts
supabase/config.toml
supabase/migrations/20250626000000_add_link_access_mission_type.sql

- リンクを開いて自動でミッションクリアする仕組みを構築
- closes #564 

リンクを開いて自動でミッションクリアする仕組みを構築

---

supabase/config.toml

最大取得件数を10000に

---

mission_data/category_links.yaml
mission_data/mission_quiz_links.yaml
mission_data/missions.yaml
mission_data/quiz_questions.yaml

政策クイズのyaml追加

---

app/api/missions/[id]/og/route.tsx

ミッションクリアのシェア画像の改行位置を修正

---

mission_data/category_links.yaml
mission_data/mission_quiz_links.yaml
mission_data/missions.yaml
mission_data/quiz_questions.yaml

100日プランのクイズを追加

---

cloudbuild.yaml

- poster:load-csv のdeploy 失敗したため

revert poster-data deploy

---

mission_data/category_links.yaml
mission_data/missions.yaml

街頭演説手伝いミッション追加

---

mission_data/category_links.yaml
mission_data/missions.yaml

本番デプロイ 07/01 13:22

---

app/map/poster/[prefecture]/PrefecturePosterMapClient.tsx
app/missions/[id]/actions.ts
lib/types/supabase.ts
mission_data/missions.yaml
supabase/migrations/20250101_add_board_id_to_poster_activities.sql

- closes https://github.com/team-mirai-volunteer/action-board/issues/815

マップから貼付完了時に自動でミッションをクリア

---

mission_data/missions.yaml

ポスティング、政党ポスターミッションを非公開

---

components/ui/dropdown-menu.tsx
components/ui/select.tsx

本番デプロイ 07/03 00:45

---

components/mission/HorizontalScrollContainer.tsx

'mission-view'

---

mission_data/missions.yaml

Update Slack link

---

supabase/migrations/20250704131600_fix_poster_boards_unique_constraint.sql

[add cascade (](https://github.com/team-mirai-volunteer/action-board/commit/aff7d715ea35f271bd7c61c2ea3cd7c160810d08)https://github.com/team-mirai-volunteer/action-board/pull/934[)](https://github.com/team-mirai-volunteer/action-board/commit/aff7d715ea35f271bd7c61c2ea3cd7c160810d08)

本番デプロイ 07/05 16:20

---

app/ranking/page.tsx
app/ranking/ranking-mission/page.tsx
app/ranking/ranking-prefecture/page.tsx
components/ranking/period-toggle.test.tsx
components/ranking/period-toggle.tsx
components/ranking/ranking-mission.tsx
components/ranking/ranking-prefecture.tsx
components/ranking/ranking-top.tsx
components/top/ranking-section.tsx
tests/e2e/user-mission.spec.ts

ランキング周りのUI調整

---

components/top/ranking-section.tsx

ランキングUI微調整

---

components/top/ranking-section.tsx

本番デプロイ 07/07 00:05

---

lib/services/badgeCalculation.ts

ミッションも上位100人にバッジ付与

---

components/ranking/ranking-mission.tsx
components/ranking/ranking-prefecture.tsx
lib/services/badges.ts

ミッションバッジのタイトルを修正

---

components/ranking/ranking-mission.tsx
components/ranking/ranking-prefecture.tsx
lib/services/badges.ts

本番デプロイ 07/07 01:03

---

components/user-badges/badge-display.tsx
lib/services/badges.ts
lib/types/badge.ts

バッジからランキングに飛べるように

---

components/user-badges/badge-display.tsx
lib/services/badges.ts
lib/types/badge.ts

本番デプロイ 07/07 01:31

---

mission_data/missions.yaml

Slack招待リンクを更新

---

cloudbuild.yaml

本番デプロイ一時対応

---

cloudbuild.yaml

Fix cloudbuild

---

cloudbuild.yaml

本番デプロイ 07/08 12:08

---

mission_data/missions.yaml

- closes https://github.com/team-mirai-volunteer/action-board/issues/959

Update clip mission

---

cloudbuild.yaml

本番デプロイ 07/09 10:24

---

app/(protected)/settings/profile/ProfileForm.tsx
components/mission/mission.test.tsx
components/mission/missions.tsx
mission_data/categories.yaml
mission_data/category_links.yaml
mission_data/missions.yaml
mission_data/quiz_questions.yaml
mission_data/src/sync.ts
mission_data/src/types.ts
supabase/migrations/20250711021743_add-featured-importance-to-missions.sql

本番デプロイ 07/11 21:50

---

app/map/poster/PosterMap.tsx
app/map/poster/PosterMapWithCluster.tsx
app/map/poster/[prefecture]/PrefecturePosterMapClient.tsx
lib/services/missionsRanking.test.ts
lib/services/prefecturesRanking.test.ts
mission_data/category_links.yaml
mission_data/missions.yaml

本番デプロイ 07/12 23:05

---

mission_data/missions.yaml

- **重要ミッションアップデート**
- **Update missions**

fix missions

---

components/metrics/index.test.tsx
components/metrics/index.tsx
mission_data/missions.yaml

本番デプロイ 07/14 12:59

---

app/map/poster/PosterMapWithCluster.tsx
app/ranking/ranking-mission/page.tsx
app/ranking/ranking-prefecture/page.tsx
app/users/[id]/page.tsx
app/users/[id]/user-detail-activities.tsx
components/activity-timeline.test.tsx
components/activity-timeline.tsx
components/metrics/index.test.tsx
components/metrics/index.tsx
lib/metadata.ts
mission_data/missions.yaml
tests/e2e/user-mission.spec.ts

本番デプロイ 07/14 22:52

---

components/mission/ArtifactForm.tsx
mission_data/missions.yaml

確認団体ビラミッションを更新

---

app/missions/[id]/actions.ts

Fix type check

---

components/mission/ArtifactForm.test.tsx
components/mission/ArtifactForm.tsx

ビラの郵便番号任意に

---

app/actions.ts

本番デプロイ 07/19 10:17

---

mission_data/missions.yaml

Fix mission text

---

components/user-mission-achievements/index.tsx
components/user-mission-achievements/mission-card.tsx

本番デプロイ 07/19 10:38

---

components/user-mission-achievements/index.tsx
components/user-mission-achievements/mission-card.tsx

本番デプロイ 07/19 11:12

---

app/map/poster/[prefecture]/PrefecturePosterMapClient.tsx

本番デプロイ 07/26 17:06

---

mission_data/src/db.ts
mission_data/src/export.ts
mission_data/src/sync.ts
scripts/export-users-prefecture.ts
src/app/(protected)/settings/profile/actions.ts
src/app/actions.ts
src/app/api/batch/backfill-missing-xp/route.ts
src/app/missions/[id]/actions.ts
src/app/missions/[id]/quiz-actions.ts
src/lib/services/badgeCalculation.ts
src/lib/services/badgeNotification.ts
src/lib/services/badges.ts
src/lib/services/levelUpNotification.ts
src/lib/services/seasons.ts
src/lib/services/userActivity.ts
src/lib/services/userLevel.ts
src/lib/services/users.ts
src/lib/supabase/adminClient.ts
src/lib/supabase/check-env-vars.ts
src/lib/supabase/server.ts
src/lib/validation/referral.ts

createServiceClient → createAdminClientに命名変更

supabaseServiceClientの命名改善

---

mission_data/missions.yaml

hide event missions

---

mission_data/missions.yaml

本番デプロイ 08/29 17:09
