README.md, app/actions.ts, app/auth/callback/route.ts, app/layout.tsx, app/missions/[id]/complete/page.tsx, app/missions/[id]/page.tsx, app/page.tsx, components/header-auth.tsx, supabase/migrations/20250510122416_add_first_tables.sql, utils/supabase/middleware.ts, utils/types/supabase.ts
related #7
ミッションの登録にはユーザーの認証状態が依存するので、一旦ログインがわかりやすくできるよう、ヘッダと、ログインボタンを表示するようにした。
また、ローカル開発時に、どのように認証ユーザーや、ユーザー関連レコードを追加すればよいかをREADMEに追記した。
トップ画面のミッション一覧から遷移できるミッション詳細画面を作り、その中で完了ボタンを押せるようにした。
なお、ログイン状態に応じて、ミッション詳細画面での完了ボタンの状態を切り替えるようにした。
1. 未ログイン状態(押せない)
2. ログイン済み(押せる)
3. すでに完了済みの場合(押せない)
ミッションを完了したあとに遷移し、完了をシェアするための画面を用意した。
シェア機能は未実装です。
=> feat: ミッションの達成を保存できるようにする

next.config.ts
fix #84
- 大きめの画像アップロードに対応するためにBodyサイズを10MB受付可能にする
=> リクエストのbodyサイズの制限を10MBに変更(デフォルト1MB)

app/(protected)/settings/profile/ProfileForm.tsx, app/(protected)/settings/profile/actions.ts, components/my-avatar.tsx, components/user-avatar.tsx, lib/avatar.ts, supabase/config.toml
fix #85 
- supabase pro plan以上で使える image transform 機能を使っています
- avatar_url にはURLではなくストレージにおけるパスを保存するようにしてます。
=> avatar画像の動的リサイズ

components/activities.tsx, components/progress.tsx, package-lock.json, package.json
バッチ集計は初期スコープ外という話だったかと思うのでオンライン集計でできる範囲でトップページの集計系の表示をしました。
=> トップページのアクション数、登録人数の取得

app/(auth-pages)/forgot-password/page.tsx, app/(auth-pages)/sign-in/page.tsx, app/(auth-pages)/sign-up/SignUpForm.tsx, app/(protected)/reset-password/page.tsx
パスワードマネージャー向けに autocomplete を設定しましょうというwarningsが出ていたので対応
参考
https://www.chromium.org/developers/design-documents/create-amazing-password-forms/
=> chromeの警告修正 。パスワードマネージャ向けの autocomplete 追加

.env.example, app/missions/[id]/complete/ShareFacebookButton.tsx, app/missions/[id]/complete/ShareLineButton.tsx, app/missions/[id]/complete/page.tsx
ミッション完了ページに、以下のSNSシェアボタンを追加しました：
- **Facebook**：すべてのデバイスで表示
- **LINE**：モバイルデバイスでのみ表示
🔗 関連Issue: https://github.com/team-mirai/action-board/issues/50
---
- `ShareFacebookButton.tsx` と `ShareLineButton.tsx` の追加
- `page.tsx` へのボタン配置と、モバイル表示の調整（Tailwindの `md:hidden` 使用）
- 余白クラスを統一し、見た目を揃えました
---
- Facebookシェアが動作すること
- LINEボタンがモバイル環境でのみ表示されること
---
TypeScript、Next.jsは学習中のため、ご指摘・改善提案あればいただけると嬉しいです 🙇‍♂️
=> Facebook、Lineのシェアボタンを追加

app/(auth-pages)/sign-up/SignUpForm.tsx, app/(protected)/settings/profile/ProfileForm.tsx, app/(protected)/settings/profile/actions.ts, app/(protected)/settings/profile/page.tsx, app/actions.ts, app/page.tsx, lib/services/users.ts, lib/types/supabase.ts, lib/utils/utils.ts, supabase/migrations/20250510122416_add_first_tables.sql, supabase/seed.sql, tests/e2e/auth.spec.ts, tests/rls/private-users.test.ts, tests/rls/utils.ts
アカウント作成時に生年月日の入力を必須化し、**18歳未満のユーザーは登録できないよう制限**を実装しました。公職選挙法の規定に従い、選挙運動への参加資格を年齢で制限することを目的としています。
- **生年月日入力の必須化**: サインアップフォームに生年月日フィールドを追加
- **18歳未満制限**: 年齢計算により18歳未満のユーザーの登録を阻止
- **リアルタイム検証**: 生年月日入力時に即座に年齢チェックを実行
- **適切なエラーメッセージ**: 年齢制限に関する法的根拠を含む分かりやすいメッセージを表示
- **年齢計算関数の追加**: `lib/utils/utils.ts`に`calculateAge()`関数を実装
- **バリデーション強化**: Zodスキーマによるサーバーサイドでの年齢検証
- **データベース更新**: `private_users`テーブルに`date_of_birth`カラムを追加
- **型定義更新**: Supabaseの型定義を更新して生年月日フィールドに対応
- **E2Eテスト**: サインアップフローでの生年月日入力テストを追加
- **RLSテスト**: 生年月日フィールドに関するRow Level Securityのテスト実装
- **エラーハンドリングテスト**: 年齢制限バリデーションのテストケースを追加
- **フォームデザイン**: 生年月日入力フィールドを追加
- **リアルタイムフィードバック**: 入力と同時に年齢チェック結果を表示
- **アクセシビリティ**: 適切なラベルとエラーメッセージでユーザビリティを向上
- ✅ **新規ユーザー登録**: 18歳以上のユーザーのみ登録可能
- ✅ **既存ユーザー**: 影響なし（既に登録済みのユーザーは引き続き利用可能）
- ✅ …
=> #124 アカウント作成時に生年月日を入力し、１８歳未満はアカウントを作れなくする

app/missions/[id]/complete/page.tsx
暫定的にFacebookシェアボタンをPC環境で隠していたのを表示するようにします
コンテキスト
[Facebook、Lineのシェアボタンを追加](https://github.com/team-mirai/action-board/pull/123)
[FacebookシェアURLがPCで正しく機能しない](https://github.com/team-mirai/action-board/issues/129)
=> PC環境でもFacebookシェアボタンを有効にする

supabase/config.toml, supabase/templates/confirmation.html, supabase/templates/email_change.html, supabase/templates/invite.html, supabase/templates/magic_link.html, supabase/templates/recovery.html
fix #67 
- いったん使ってないものも含めて全部設定しておきました
- publicな場所にロゴ画像がまだ配備されていないため、政党LPのページに直リンクさせてもらってます。
デザイン
=> メールテンプレートの設定

app/(auth-pages)/sign-in/page.tsx, app/(auth-pages)/sign-up/SignUpForm.tsx, app/actions.ts, components/form-message.tsx
- パスワード誤り時のメッセージが日本語になるように修正
- メッセージ表示位置をボタンの下からフォームの上に変更
- メッセージのUIをレベルが背景色で分かるように修正
- メッセージが目立たず次のアクションが取りづらくなるため
=> サインイン/サインアップのメッセージ周りのUI改善

supabase/config.toml
- 127.0.0.1 に対してクッキーが付与され、その後 localhost にリダイレクトされるのでクッキー付与されない動作になっていた。
- ローカル環境でサインアップ後に自動ログインできない
=> ローカル環境でサインアップ後に自動ログインできない問題の修正

app/users/[id]/page.tsx, components/user-avatar.tsx, lib/avatar.ts
- アバターアイコン表示の不具合修正
- アバターアイコンが表示されていなかった
- サイズが小さすぎた
=> ユーザー詳細のアバターに関する修正

app/(protected)/settings/profile/ProfileForm.tsx
fix #135 
profileの生年月日をDatePickerからselectbox方式に変更しました
- 「年」の最も若い（つまり最大の）年は2007年としています、これは2025年現在で18歳以上は全て2007年以前の生まれである必要があるからです
- 「年・月」から換算し、日に不正値が入る可能性がある場合は日をリセットする処理を入れています（1月31日を選択→2月を選択した時に2月31日が指定できないようにする処理）
https://github.com/user-attachments/assets/eeeebdb7-e3fb-477d-9ee1-292297c23319
- issueにて報告があったため
=> feat: 生年月日をselectboxに変更

app/(auth-pages)/sign-in/SignInForm.tsx, app/(auth-pages)/sign-in/page.tsx, app/(auth-pages)/sign-up/SignUpForm.tsx, app/actions.ts, jest.config.js, lib/validation/auth.ts, tests/validation/auth.test.ts
- サインアップ時にパスワード要件の明示 (8桁以上 英数を含む 一部記号が使える)
- パスワード要件のバリデーション実装
- エラーでサインアップフォームの内容が消える不具合の修正
fix #161 
- パスワードの要件が不明だった
=> パスワード要件の明示とバリデーション

supabase/migrations/20250510122416_add_first_tables.sql, supabase/seed.sql
- シードデータに初期のミッションを追加
- 現在、シードデータには機能開発のため多様なミッションデータが入っている。もしかしたらサービス稼働前に必要なシードデータは、は別のsqlファイルに切り出すかも
- #34 の実現のため
=> feat: 初期のミッションをmigrationデータに追加

cloudbuild.yaml, terraform/nextjs-app/secrets.tf
- terraform の secrets と cloudbuild.yaml の参照を合わせる
- 環境変数のリファクタを行ったときに変更し忘れている。(build に失敗している)
=> fix secrets naming in cloudbuild.yaml and terraform files

app/missions/[id]/_components/CancelSubmissionDialog.tsx, app/missions/[id]/_components/MissionFormWrapper.tsx, app/missions/[id]/_components/MissionWithSubmissionHistory.tsx, app/missions/[id]/_components/SubmissionHistory.tsx, app/missions/[id]/_components/SubmissionItem.tsx, app/missions/[id]/_hooks/useMissionSubmission.ts, app/missions/[id]/_lib/data.ts, app/missions/[id]/actions.ts, app/missions/[id]/page.tsx, components/mission/ArtifactForm.tsx, components/mission/GeolocationInput.tsx, components/mission/MissionDetails.tsx, components/mission/mission.tsx, components/ui/mission-icon.tsx, lib/artifactTypes.ts
- 横幅を制限
- 「提出する」=>「達成を報告する」という言い回しに変更
- 言い回しがバラバラだったり堅苦しいところの修正
- 横長すぎるフォームやボタンを小さくまとめた
=> ミッション画面のデザイン改善

.env.example, supabase/config.toml
- Supabaseのクラウドホスティング環境で新規登録ユーザーにメールを送るためにCustom SMTP設定が必要である。それを環境変数経由で取り回すように対応
- ChatGPT曰く、config.tomlにある[auth.email.smtp]は、Supabaseのクラウド環境でのみ有効になるらしい。そのため、enabled = trueと設定している。
- #167 
- #168
=> feat: Custom SMTP設定をsupabase/config.tomlに追加

app/(auth-pages)/sign-up/SignUpForm.tsx, app/(protected)/settings/profile/ProfileForm.tsx, tests/e2e/auth.spec.ts
fix: #135 
前回誤った部分を修正してしまっていたので改めてPRを出します
- `SignUpForm.tsx` の 生年月日をInputからSelectへ変更
- 年齢チェック部分で既存コードを一部削除してる点がわかりにくいと思うので対象コードに↓でコメントします
- 誤って変更してしまった`ProfileForm.tsx` をInputのreadonlyへ元に戻す
https://github.com/user-attachments/assets/b326ebb7-a847-4acf-a84d-30b7b504148e
- issueが上がっていたため対応
=> feat: SignUpFormをInputからSelectBoxへ変更

terraform/cloud_build.tf, terraform/main.tf, terraform/nextjs-app/secrets.tf, terraform/variables.tf
github org を team-mirai-volunteer を向くように変更 & その他細かいリファクタ
組織が変わったので github-connection を作成し直しました
=> github org を team-mirai-volunteer を向くように変更 & その他細かいリファクタ

app/privacy/page.tsx, app/terms/page.tsx
- タイトル通り
PCでの表示
モバイルでの表示
- Closes #38 
- Closes #40 
=> feat: 利用規約とプライバシーポリシーを追加

.github/CODEOWNERS
- タイトル通り
- https://team-mirai-volunteer.slack.com/archives/C08SNQ7D29L/p1748065690556769 このメッセージで、CODEOWNERSへの追加を確認。
=> fix: codeownersの記法が間違っていたのを修正

app/missions/[id]/actions.ts
本番で以下のエラーが発生していた。
全体の上限回数と個人のクリア回数のロジックがごちゃまぜになってバグになっていた。
そもそも全体の上限回数をつける予定がないので、機能ごと削除しました。
=> 全体の上限回数ロジックを削除

app/layout.tsx, lib/metadata.ts
- Unsupported metadata viewport is configured in metadata export in /.  
Please move it to viewport export instead.                              
Read more:                                                              
https://nextjs.org/docs/app/api-reference/functions/generate-viewport   
というwarningが表示されたので、上記URLにしたがって修正
- #242
=> fix: viewport設定でエラーが出るのでnext.jsのdocにしたがって修正

app/actions.ts
- タイトル通り
- パスワードリセットのメールなどを送った際に英語メッセージが出るのが気になったので
=> fix: actions.tsにあるnotificationメッセージを日本語化

app/globals.css, app/layout.tsx, lib/metadata.ts
- geistフォントという英語向けのフォントが適用されていたので、hiragino sans JPに変更
- フォールバックフォントのhiragino kaku gothicはfont weight 400と700しか定義できず、もう少し細めのboldも使いたい部分があるので、hiragino sansを使用。
- [x ] CLAの内容を読み、同意しました
=> feat: update font to hiragino sans.

biome.json
- biomeの設定でplaywright-reportを無視するために`biome.json`を修正
- `npm run test:e2e`を実行すると`playwright-report`フォルダが作成される。しかし、biomeはそのフォルダ内のファイルも対象となる。そのため、`biome:check:write`に時間がかかり処理が終わらない。
=> biomeの設定でplaywright-reportを無視する

supabase/templates/confirmation.html, supabase/templates/email_change.html, supabase/templates/invite.html, supabase/templates/magic_link.html, supabase/templates/recovery.html
- メールテンプレートのボタンの色を単色、emerald-600(#059669)相当に変更
- linear-gradientをサポートしていないメールソフトに対応するため
Yahoo!メール(Web)で表示されることを確認しました。
**以下は対応前**
=> #305 メールテンプレートのボタンの色を単色、emerald-600(#059669)相当に変更

.env.example, app/api/batch/backfill-missing-xp/route.ts, lib/services/userLevel.ts
- XPが付与されていないミッション達成データにポイントを遡及的に付与するバッチ処理APIを追加
- 新しいAPIエンドポイント `/api/batch/backfill-missing-xp` を実装
- 管理者認証機能とバッチ処理結果のレポート機能を含む
- 環境変数 `BATCH_ADMIN_KEY` を追加してセキュリティを確保
- `app/api/batch/backfill-missing-xp/route.ts` (新規作成)
- `.env.example` (管理者キーの設定例を追加)
- ミッション達成時にXP（経験値）が正常に付与されない問題が発生していた
- 既存のミッション達成データでXPトランザクションが記録されていないものが存在
- 過去の達成データに対してもXPを適切に付与する必要があった
- データの整合性を保ちながら、安全に遡及処理を実行する仕組みが必要だった
- **認証**: `BATCH_ADMIN_KEY` による管理者認証
- **処理内容**:
1. XPトランザクションが記録されていないミッション達成を検索
2. 各達成にミッション難易度に応じたXPを付与（★1: 50XP, ★2: 100XP, ★3: 200XP）
3. 処理結果の詳細レポートを返却
- **セーフティ機能**:
- レート制限を考慮した100ms間隔での処理
- エラーハンドリングと詳細なログ出力
- 既にXPが付与済みの達成はスキップ
- **認証**: 不要（統計情報の確認用）
- **機能**: XP未付与の達成数と完了率の統計情報を返却
- **用途**: バッチ処理実行前の状況確認や実行後の確認
- TypeScriptで型安全性を確保
- Supabaseを使用したデータベース操作
- 既存の `grantXp` 関数と …
=> #289 バッチ処理で達成済みのミッションに対してポイントを付与する

terraform/nextjs-app/cloud_build.tf
- build ステップで `_ENVIRONMENT` を参照できるようにする
- 秘匿情報以外はアプリ側で管理してしまったほうが開発サイクルがはやくなりそうなので、環境名を取得できるようにしておく
=> Pass ENVIRONMENT to Cloud Build Trigger

app/missions/[id]/_components/MissionFormWrapper.tsx
- クリア上限のないミッションにおいても、一度達成したらシェアできるようにする。
- 達成回数が決まっているミッションしかシェア画面が出ない現状だった。
下記のように、他のページと同様に表示されるように修正しているのですが、達成報告の箇所に組み込む方が適切でしょうか？
fixes #316
=> クリア上限なしのミッションでも、あとからシェアできるようにする

lib/validation/referral.ts
- バグ修正。紹介経由で、同一アドレスでのサインアップ時にachivements、mission_artifactsへデータが登録されないようにする
- バグ修正
=> 紹介ミッション 同一アドレスサインアップ時達成テーブル登録スキップ

next.config.ts
- build 時に .git の情報を参照しないようにする。
- 必要な情報は外から渡している & cloud build 時には .git は渡さないようにしているので取れなくてエラーになる
=> make setCommits false in next.config.ts

components/levels.tsx
- 他人のユーザー詳細ページのアイコンが自分のが表示されていたので、他人のユーザーのアイコンに設定
- https://github.com/team-mirai-volunteer/action-board/issues/368
=> MyAvatarからUserAvatarに置き換えてアバター表示を統一

app/missions/[id]/actions.ts, lib/services/userLevel.ts, lib/types/supabase.ts, supabase/migrations/20250609000000_add_mission_cancellation_source_type.sql, tests/services/userLevel.test.ts, tests/utils/utils.test.ts
- ミッション取り消し時にXPを減算
- MISSION_CANCELLATIONという新しいsource_typeをxp_transactionsに追加
- https://github.com/team-mirai-volunteer/action-board/issues/369
=> fix: ミッション提出取り消し時のXP減算を実装してレベルアップ無限バグを修正

CLAUDE.md
- CLAUDE.mdの更新
- 前回作成されてから機能が追加されているため
=> Add comprehensive CLAUDE.md for development guidance

app/terms/page.tsx
=> fix: 利用規約から日本国内に居住していることについての文言を省く

supabase/migrations/20250612000000_fix_posting_mission_ogp_url.sql
- 機関紙ポスティングのOGP画像のURL修正
- URLが想定と違ったので修正
=> 機関紙ポスティングのOGP画像のURL修正

supabase/migrations/20250611082230_add_mission_join_slack.sql
- 追加ミッション: サポーターSlackに入ろう
- https://team-mirai.notion.site/Slack-20af6f56bae18057a13ed6e7cd198a11
- closes #378
- icon_url が mission_fallback.svg のミッションと mission_fallback_icon.svg のミッションがあるようで、使い分けがよくわかりませんでしたが、本番で使われているのは前者のみのようですし前者のほうが新しくできたもののようなので、後者が前者ができるまでに仮で使われていたものなのかと判断して前者を設定しました。この判断が正しければ後者を設定しているレコードは書き換え、後者のアイコンも削除して良いと思いました。
- content はチームみらい運営から送られたサポーター向けメールの文章を元にしています。
- content に Slack ワークスペースへのリンクを張るかを悩み、張りませんでした。アクションボードは公開されているため、サポーター外のメンバーもアクセスできるからです。同時に LINEオープンチャットの URL が公開されているのは良いのかなと疑問に思いました。運営の承認を挟むので問題ないという判断でしょうか？Slack は運営の承認挟んでましたっけ？
- 「Slack に入ろう」だけでなく、Slack …
=> 追加ミッション: サポーターSlackに入ろう

cloudbuild.yaml
supabase db push コマンドに --include-all を付与。
これによって適用されている最新のマイグレーションよりも古いマイグレーションファイルもマイグレーション実行することになります。
- developブランチにマージするタイミングがまちまちなので、しょっちゅう--include-allを自分の手元でstagingのSupabaseにやってるが運用辛い
- マイグレーションは意図した順番で実行されるべき、というのは本来あるが、運用上--include-allを手元でやるデメリットのほうが大きい
=> CIのマイグレーションでinclude-all

supabase/migrations/20250624081700_add_slug_to_missions.sql, supabase/seed.sql
- missionsテーブルにslugを追加しました
- 今までidやタイトルで指定していたが、↓の理由から特定のmissionを指し示すのには不適切
- idは環境ごとに違う場合がある
- タイトルは文言調整などで変わりやすい
=> missionsテーブルにslugを追加

app/users/[id]/page.tsx
- w-full をつけることで、コンテンツが画面幅に収まるようにしました
- /users/{usersId}で横スクロールが発生していたため
- closes #655
（念の為 PC 表示）
=> #655: /users/{usersId}で横スクロールが発生する

components/metrics/donation-metric.tsx, components/metrics/supporter-metric.tsx
- チームみらいの活動状況ページにGoogle Looker Studioのダッシュボードリンクを追加
- サポーター数の部分に登録数ダッシュボードへの「詳細を見る」リンクを追加
- 寄付金額の部分に寄付金額ダッシュボードへの「詳細を見る」リンクを追加
- 既存の「ご支援はこちらから」リンクは維持
- 活動状況ページにて、サポーター数と寄付金額の詳細データを確認したいユーザーのニーズに応えるため
- Google Looker Studioで作成されたダッシュボードへの導線を追加することで、より詳細な分析データを提供
- 既存のリンク構造を維持しながら、新しい詳細リンクを追加することで機能拡張を実現
- closes #1118
=> feat: チームみらいの活動状況にダッシュボードリンクを追加

mission_data/missions.yaml
- tiktok-clip-final-pushのfeatured_importanceを1000→100に変更
- マイク納めミッション(featured_importance: 110)が最上位表示になるよう調整
- upstreamマージにより新しく追加されたtiktok-clip-final-pushミッションのfeatured_importance: 1000により、マイク納めミッション(110)の表示順位が下がった
- issue #1224 で要求されたマイク納めの最上位表示を維持するため調整が必要
- https://github.com/team-mirai-volunteer/action-board/issues/1224#issuecomment-3076648278
=> chore: tiktok-clip-final-pushのfeatured_importanceを調整

mission_data/missions.yaml
refs #1224
- tiktok-clip-final-pushのfeatured_importanceを1000→100に変更
- マイク納めミッション(110)が最上位表示になるよう調整
=> 本番デプロイ 07/16 13:12

mission_data/missions.yaml
平時のSlackの運用方針がまだ定まってないので、一旦非表示に
=> Slackジョイン系のミッションをhide
